[package]
name = "gpt2"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = {version = "1.0.206" , features=["derive"]}
thiserror = "1.0.63"
